spring.datasource.url=jdbc:postgresql://localhost:5432/company_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.generate-ddl=true
server.port=8080

token=btqbebn48v6t9hdd6cog
exchange=US

jwt.secret=finnhubsecret
jwt.expired=3600000