spring.datasource.url=jdbc:postgresql://localhost:5432/company_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.generate-ddl=true
server.port=8080

token=btqbebn48v6t9hdd6cog
exchange=US

jwt.secret=finnhubsecret
jwt.expired=3600000

spring.mail.host = smtp.gmail.com
spring.mail.username = marcosatan41@gmail.com
spring.mail.password = {password}

spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.socketFactory.port = 465
spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback = false

paypal.mode=sandbox
paypal.client.id=AcI-vgkQ2nULdGDAGm2i3cAqexcaSc2F9Nes7aOCbH073rNUY4q_-t3ZWYzztAd-H4wXu53--LRXf3qu
paypal.client.secret=EIJetOdzNbEdNbHfx5Vg7h46PKj9qCE2qAa5dFSu2NgYyZMJV2-XBC9Ea68gTnVKaM469451uNy-BsiC

paypal.success.url=http://localhost:8080/subscription/success/
paypal.cancel.url=http://localhost:8080/subscription/cancel/
paypal.currency=USD
paypal.method=PAYPAL
paypal.intent=SALE