spring.datasource.url=jdbc:postgresql://localhost:5432/company_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.generate-ddl=true

token=btqbebn48v6t9hdd6cog
exchange=US