spring.datasource.url=jdbc:postgresql://db:5432/company_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.generate-ddl=true
server.port=8081
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

token=btqbebn48v6t9hdd6cog
exchange=US
